name: Deploy to Digital Ocean

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # - name: Checkout Repo
      #   uses: actions/checkout@v2

      # - name: Install Dependencies
      #   run: npm install

      # - name: Build
      #   run: npm run build

      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Deploy to Digital Ocean
        run: |
          ssh -o StrictHostKeyChecking=no [your-username]@[your-droplet-ip] << 'ENDSSH'
            cd /var/www/forage-abq
            git pull origin main
            npm install
            npm run build
          ENDSSH
