name: Deploy to Digital Ocean

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Deploy to Digital Ocean
        run: |
          ssh -o StrictHostKeyChecking=no snailbones@104.248.65.121<< 'ENDSSH'
            source ~/.nvm/nvm.sh
            nvm use 20
            which node
            which npm
            cd /var/www/forage-abq
            git pull origin main
            npm install
            npm run build
          ENDSSH
